// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC71APupMyf1yvJYLvJxfbUTs2FQpoy7Mo',
    appId: '1:780979365314:web:f0005852d491ad012ca25b',
    messagingSenderId: '780979365314',
    projectId: 'pashewfood',
    authDomain: 'pashewfood.firebaseapp.com',
    databaseURL: 'https://pashewfood-default-rtdb.firebaseio.com',
    storageBucket: 'pashewfood.appspot.com',
    measurementId: 'G-T57BJNZD9Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0p3ZuMT1_wzOfScUVPFLzeZDSuONw_Kc',
    appId: '1:780979365314:android:80b6b3f63b5349872ca25b',
    messagingSenderId: '780979365314',
    projectId: 'pashewfood',
    databaseURL: 'https://pashewfood-default-rtdb.firebaseio.com',
    storageBucket: 'pashewfood.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAneZ6aoPsIdm1jWL50pCY3gbmhqWOLBW4',
    appId: '1:780979365314:ios:bbf13a8c70bede002ca25b',
    messagingSenderId: '780979365314',
    projectId: 'pashewfood',
    databaseURL: 'https://pashewfood-default-rtdb.firebaseio.com',
    storageBucket: 'pashewfood.appspot.com',
    androidClientId: '780979365314-n2aknuvbfb9bntqfq34th456ht170j09.apps.googleusercontent.com',
    iosClientId: '780979365314-nou1ddo3scnuuic70r3t1if65koulklp.apps.googleusercontent.com',
    iosBundleId: 'com.example.manager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAneZ6aoPsIdm1jWL50pCY3gbmhqWOLBW4',
    appId: '1:780979365314:ios:ac2ee6cd7bdee5f82ca25b',
    messagingSenderId: '780979365314',
    projectId: 'pashewfood',
    databaseURL: 'https://pashewfood-default-rtdb.firebaseio.com',
    storageBucket: 'pashewfood.appspot.com',
    androidClientId: '780979365314-n2aknuvbfb9bntqfq34th456ht170j09.apps.googleusercontent.com',
    iosClientId: '780979365314-k98iue8iibm1e0gjhj3kp96c1nvum8fq.apps.googleusercontent.com',
    iosBundleId: 'com.example.manager.RunnerTests',
  );
}
